/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author strike
 */
public class Proje extends javax.swing.JFrame {

    /**
     * Creates new form TelaExercicio
     */
    public Proje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        btnLerCsv = new javax.swing.JButton();
        btnAnalisar = new javax.swing.JButton();
        btnAnalisar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "A"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDados);

        btnLerCsv.setText("Ler CSV");
        btnLerCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerCsvActionPerformed(evt);
            }
        });

        btnAnalisar.setText("Analisar");
        
        JComboBox comboBox = new JComboBox();
        comboBox.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"Turno_Matricula = Turno", "Situacao_Civil_Aluno", "Sexo_Aluno", "Data_cadastro_requerimento", "Motivo_requerimento", "Turma", "Area_Turma"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(btnLerCsv)
        					.addGap(26)
        					.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        					.addComponent(btnAnalisar)
        					.addGap(32)))
        			.addGap(13))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnLerCsv)
        				.addComponent(btnAnalisar)
        				.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(32, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List dadosCsv = new ArrayList();

    private void btnLerCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerCsvActionPerformed
        JFileChooser selecaoArquivo = new JFileChooser();
        selecaoArquivo.showOpenDialog(this);
        File arquivoCsv = selecaoArquivo.getSelectedFile();
        System.out.println("Arquivo csv: " + arquivoCsv);

        try {
            dadosCsv.clear();

            BufferedReader br = null;
            String line = "";
            String cvsSplitBy = ",";
            br = new BufferedReader(new FileReader(arquivoCsv));
            while ((line = br.readLine()) != null) {
                String[] coluna = line.split(cvsSplitBy);
                dadosCsv.add(coluna);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Dados foram lidos do csv " + dadosCsv);
        atualizarDadosTabela();
    }//GEN-LAST:event_btnLerCsvActionPerformed

    public void atualizarDadosTabela() {
        DefaultTableModel tableModel = new DefaultTableModel();

        if (!this.dadosCsv.isEmpty()) {
            Object[] primeiraLinha = (Object[]) this.dadosCsv.get(0);
            tableModel.setColumnCount(0);

            for (Object coluna : primeiraLinha) {
                tableModel.addColumn("" + coluna);
            }

            for (int i = 1; i < this.dadosCsv.size(); i++) {
                Object dado = this.dadosCsv.get(i);
                tableModel.addRow((Object[]) dado);
            }
        }
        this.tblDados.setModel(tableModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proje.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proje.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proje.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proje.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proje().setVisible(true);
            }
        });
    }
    private javax.swing.JButton btnAnalisar;
    private javax.swing.JButton btnLerCsv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDados;
}
